name: pocket_server
description: A local server and file sharing app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.0
  qr_flutter: ^4.1.0

flutter:
  uses-material-design: true
